# Generated by Django 5.2 on 2025-04-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='fornecedor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('FOSSIL', 'Fóssil'), ('ARTESANATO', 'Artesanato'), ('MINERAL', 'Mineral'), ('OUTRO', 'Outro')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
    ]
