# Generated by Django 5.2 on 2025-04-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_horario_atualizacao_produto_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='endereco_estoque',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
