# Generated by Django 5.2 on 2025-04-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_endereco_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='fornecedor_antigo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='preco_custo_antigo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='quantidade_antiga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
