# Generated by Django 5.2 on 2025-04-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_movimentacaoestoque_fornecedor_antigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='endereco_estoque',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
