# Generated by Django 5.2 on 2025-04-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_movimentacaoestoque_endereco_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='preco_custo_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
