# Generated by Django 5.2 on 2025-04-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_movimentacaoestoque_preco_custo_atual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacaoestoque',
            options={'ordering': ['-data_movimentacao'], 'verbose_name': 'Movimentação de Estoque', 'verbose_name_plural': 'Movimentações de Estoque'},
        ),
        migrations.RenameField(
            model_name='movimentacaoestoque',
            old_name='fornecedor_antigo',
            new_name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='preco_custo_antigo',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='preco_custo_atual',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='quantidade_antiga',
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
