# Generated by Django 5.2 on 2025-05-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='custo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
